import the libraries like cv2(opencv ) to read and write the images and reshape the images and os libraries to read the write the files from the local file system we can access the directories in the local system and numpy libraries are used to manuplate the array 
in cv2 libraries we have some inbuilt face recognition functions eigne faces,lbpg modules and fisher facess 

In [1]:
import cv2
import os
import numpy as np


first of all we have to prepare the data in the folder i arrange the different persons images in different folders like s1,s2,s3......s24
create the subject list that contain the persons names 
below code i save the first element as null because i saving the persons name from the s1 

In [2]:
subjects = ["","ab","bhumra","bindu","chahal","chiru","dhawan","dhoni","gayle","indu","koti","narayana","prabhas","rajini","rana","ravi","redd","rohit","sachin","samar","siva","surya","velu","venkey","vk"]

below the function detect_face() function to detect the human faces in the photos 
in line 2 i convert the colour image to gray image and store the image in the gray
in line 3 use the haarcascade classifier to detect the faces in the photo haarcascade to find the positive images like face eyes in the image
line 4 detect multiscale to detect the faces more than 1 in the image here scalefactor is 1.3 and minneighbours if minneighbours is less than 5 it detect more false faces 
in line 5 if the length of the faces is zero it means the detector detect null it returns the null value
in line 7 x,y,w,h are the co-ordinates to find the face height and width x,and y co-ordinates
the function return the face from the image

In [3]:
def detect_face(img):
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    face_cascade = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')
    faces = face_cascade.detectMultiScale(gray, scaleFactor=1.3, minNeighbors=5);
    if (len(faces) == 0):
        return None, None
    (x, y, w, h) = faces[0]
    return gray[y:y+w, x:x+h], faces[0]
    

here i wrote an another function that take the directory path and create the dataset and store the faces in list called faces
in line 2 load the directory path in the dirs variable
in line 3,4  we create two lists faces and labels
line 5 here we use an forloop to read the directories name one by one 
line 6 if condition to skip the directories which doesnot start with s because we save the folders start with s 
line 8 store the labels in the label and remove the s lettor from the folder and store the remaining lettor as int
line 9 here we create the subdirectories data folders + forward slash to read the inside the folder
line 10 subject images in the sub directories 
line 11 here we use the for loop to iterate the image names in the subfolders
line 12 if condition to avoid the image names start with the .
line 13 image path variable to store the image path 
line 14 image variable to read the image 
line 15 cv2 .wait key(100) to wait the 100 ms 
line 16 here we use call the detect_face() function to find the faces in the images
line 17 if condition to store the faces and labels are not null
this function to return the faces and labels lists

In [4]:
def prepare_training_data(data_folder_path):
    dirs = os.listdir(data_folder_path)
    faces = []
    labels = []
    for dir_name in dirs:
        if not dir_name.startswith("s"):
            continue;
        label = int(dir_name.replace("s", ""))
        subject_dir_path = data_folder_path + "/" + dir_name
        subject_images_names = os.listdir(subject_dir_path)
        for image_name in subject_images_names:
            if image_name.startswith("."):
                continue;
            image_path = subject_dir_path + "/" + image_name
            image = cv2.imread(image_path)
            cv2.imshow("Training on image...", image)
            cv2.waitKey(100)
            face, rect = detect_face(image)
            if face is not None:
                faces.append(face)
                labels.append(label)
                cv2.destroyAllWindows()
                cv2.waitKey(1)
                cv2.destroyAllWindows()
    return faces, labels
                

from the below cell first line is to call the training_data function to prepare the training data and give the path of the irectore where we store the images 
and print the length of the list faces and labels in the line 2 and 3

In [5]:
faces, labels = prepare_training_data("C:/Users/ntadi/Desktop/New folder/projectz")
print("Total faces: ", len(faces))
print("Total labels: ", len(labels))

Total faces:  799
Total labels:  799


below code is to print the faces list

In [6]:
faces

[array([[16, 73, 40, ..., 73, 71, 87],
        [26, 70, 14, ..., 60, 64, 77],
        [18, 67, 32, ..., 58, 76, 90],
        ...,
        [ 6,  7,  8, ...,  1,  0,  3],
        [ 7, 10, 12, ...,  0,  2,  4],
        [20, 43, 62, ...,  0,  6,  1]], dtype=uint8),
 array([[ 30,  46,  35, ...,  56,  57,  60],
        [ 24,  70,  71, ...,  55,  57,  59],
        [ 18,  92,  91, ...,  55,  57,  59],
        ...,
        [159, 136, 155, ..., 189, 189, 190],
        [168, 147, 152, ..., 189, 190, 190],
        [180, 146, 147, ..., 190, 190, 191]], dtype=uint8),
 array([[69, 70, 70, ..., 62, 62, 62],
        [70, 71, 71, ..., 62, 62, 62],
        [71, 72, 72, ..., 62, 62, 62],
        ...,
        [68, 68, 68, ..., 94, 88, 86],
        [67, 68, 68, ..., 91, 90, 90],
        [67, 67, 67, ..., 90, 92, 92]], dtype=uint8),
 array([[116, 122, 181, ..., 189, 189, 177],
        [103, 102, 188, ..., 196, 199, 178],
        [121, 110, 201, ..., 198, 200, 180],
        ...,
        [ 17,  34,  35, ...,  

below line is to print the labels 

In [7]:
labels

[1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 13,
 13,
 13,
 13,
 13,
 13,
 13,
 13,
 13,
 13,
 13,
 13,
 13,
 13,
 13,
 13,
 13,
 13,
 13,
 13,
 13,
 13,
 13,
 13,
 13,
 13,
 13,


here we use the lbph face recog nizer to train the data 
lbph facerecognizer is the inbuilt library of the open cv here it take the train images and find the centre pixel value and map the neighbor pixel values to binary values 0 and 1 if the neighbour value is graterthan or equal to centre pixel it map to 1 and if the neighbour value less than the centre value it map to 0 and convert the matrix into array
in line 1 we create an face recognizer 
in line to give the faces and labels lists to train the recognizer

In [8]:
face_recognizer = cv2.face.LBPHFaceRecognizer_create()
face_recognizer.train(faces, np.array(labels))

here we store the face recognizer as the yml file we can re use the model without training data

In [9]:
face_recognizer.save('trainData.yml')

draw_rectangle() function to draw the rectangle arround the face
here x,y,w,h coordinates are the height,width and x and y co ordinates and (0,255,0 ) color of the rectangle and 2 is the thicknes of the rectangle frame

In [10]:
def draw_rectangle(img, rect):
    (x, y, w, h) = rect
    cv2.rectangle(img, (x, y), (x+w, y+h), (0, 255, 0), 2)

draw the test around the rectsngle frame 


In [11]:
def draw_text(img, text, x, y):
    cv2.putText(img, text, (x, y), cv2.FONT_HERSHEY_PLAIN, 1.5, (0, 255, 0), 2)


here we write another function to predict the image 
in line 2 copy the imge we want to predict 
in line 3  to find the face of the image by fed the image into detect_face() function 
in line 4 store the predicted image into label variable
in line 5 store the text we have to draw top of the rectangle frame to label_text variable
in line 6 draw_rectangle() function to draw the rectangle around the face of the image
in line 7 draw the predicted label around the predicted image


In [12]:
def predict(test_img):
    img = test_img.copy()
    face, rect = detect_face(img) 
    label= face_recognizer.predict(face)
    #print("confidence",confidence)
    label_text = subjects[np.array(label[0])]
    draw_rectangle(img, rect)
    draw_text(img, label_text, rect[0], rect[1]-5)
    return img

here we read the image we want to predict by the cv2.imread() function  

In [13]:
test_img1 = cv2.imread('C:/Users/ntadi/Desktop/New folder (2)/test/vk-1.jfif')
test_img2 = cv2.imread('C:/Users/ntadi/Desktop/New folder (2)/test/narayana2.jpeg')
test_img3=cv2.imread('C:/Users/ntadi/Desktop/New folder (2)/test/tnr.jpeg')

here we find the predicted image results in to the predicted_img variable it calls the predict function and return the predicted image 

In [14]:
predicted_img1 = predict(test_img1)
predicted_img2 = predict(test_img2)
predicted_img3=predict(test_img3)
print("Prediction complete")

Prediction complete


here we use cv2.imshow() function to show the predicted image destroy all windows to stop running the code 

In [ ]:
cv2.imshow(subjects[0], predicted_img1)
cv2.imshow(subjects[1], predicted_img2)
cv2.imshow(subjects[2], predicted_img3)
cv2.waitKey(0)
cv2.destroyAllWindows()