# Exercises - Numpy
# NumPy is the fundamental package for scientific computing with Python. 
useful linear algebra, Fourier transform, and random number capabilities




# NumPy Array Attributes
First let's discuss some useful array attributes. We'll start by defining three random arrays, a one-dimensional, two-dimensional, and three-dimensional array. We'll use NumPy's random number generator, which we will seed with a set value in order to ensure that the same random arrays are generated each time this code is run:

In [1]:
import numpy as np
np.random.seed(0)  # seed for reproducibility

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

In [2]:
x1

array([5, 0, 3, 3, 7, 9])

In [3]:
x1[0]

5

In [4]:
# in a multi-dimensional array, items can be accessed using a comma-separated tuple of indices:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [5]:
x2[0, 1]

5

In [6]:
x2[2, 0]

1

In [9]:
x2[2, -4]

1

In [34]:
#Values can also be modified using any of the above index notation:
x2[0, 0] = 12
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

# Array Slicing: Accessing Subarrays
Just as we can use square brackets to access individual array elements, we can also use them to access subarrays with the slice notation, marked by the colon (:) character. The NumPy slicing syntax follows that of the standard Python list; to access a slice of an array x, use this:

## x[start:stop:step]
If any of these are unspecified, they default to the values start=0, stop=size of dimension, step=1. We'll take a look at accessing sub-arrays in one dimension and in multiple dimensions.

In [35]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
x[:5]  # first five elements

array([0, 1, 2, 3, 4])

In [37]:
x[5:]  # elements after index 5

array([5, 6, 7, 8, 9])

In [38]:
x[4:7]  # middle sub-array

array([4, 5, 6])

In [39]:
x[::2]  # every other element

array([0, 2, 4, 6, 8])

# Multi-dimensional subarrays
Multi-dimensional slices work in the same way, with multiple slices separated by commas. For example:

In [40]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [41]:
x2[:2, :3]  # two rows, three columns

array([[12,  5,  2],
       [ 7,  6,  8]])

In [42]:
x2[:3, ::2]  # all rows, every other column

array([[12,  2],
       [ 7,  8],
       [ 1,  7]])

In [43]:
#Finally, subarray dimensions can even be reversed together:
x2[::-1, ::-1]

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])

# Accessing array rows and columns
One commonly needed routine is accessing of single rows or columns of an array. This can be done by combining indexing and slicing, using an empty slice marked by a single colon (:):

In [44]:
print(x2[:, 0])  # first column of x2

[12  7  1]


In [45]:
print(x2[0, :])  # first row of x2

[12  5  2  4]


In [46]:
#In the case of row access, the empty slice can be omitted for a more compact syntax:
print(x2[0])  # equivalent to x2[0, :]

[12  5  2  4]


# Reshaping of Arrays
Another useful type of operation is reshaping of arrays. The most flexible way of doing this is with the reshape method. For example, if you want to put the numbers 1 through 9 in a  3×3  grid, you can do the following:

In [47]:
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
