In [1]:
class Account: #abstraction
    bal = 0
    def deposit(self):
        print ("my balance is {}".format(self.bal)) 

In [2]:
ravi = Account()
print (type(ravi))     # Instance/Object
print (type(Account))   # classobj/class
print (type(Account()))
print (dir(ravi))

<class '__main__.Account'>
<class 'type'>
<class '__main__.Account'>
['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', 'bal', 'deposit']


In [6]:
nani=Account()
print(type(nani))
print(type(Account))
print(dir(nani))

<class '__main__.Account'>
<class 'type'>
['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', 'bal', 'deposit']


In [7]:
ravi.bal

0

In [8]:
nani.bal

0

In [9]:
ravi.deposit()

my balance is 0


In [10]:
nani.deposit()

my balance is 0


In [11]:
class BAccount:
    def __init__(self):  # constructor
        self.Nbal = 0
    def deposit(self,amount):
        self.Nbal = self.Nbal + amount
        return "my balance is {}".format(self.Nbal)
    def withdraw(self,amount):
        self.Nbal = self.Nbal - amount
        return "my balance is {}".format(self.Nbal)

In [12]:
class Bac:
    def __init__(self):
        self.bal=0
    def deposit(self,amount):
        self.bal=self.bal+amount
        return "my balance is {}".format(self.bal)
    def withdraw(self,amount):
        self.bal=self.bal-amount
        return 'mybalance is {}'.format(self.bal)

In [13]:
nani=Bac()

In [14]:
nani

In [15]:
nani.deposit(2345)

'my balance is 2345'

In [16]:
nani.withdraw(200)

'mybalance is 2145'

In [17]:
class Consumer:
    
    def __init__(self, w):
        "Initialize consumer with w dollars of wealth"
        self.wealth = w
        
    def earn(self, y):
        "The consumer earns y dollars" 
        self.wealth += y
        
    def spend(self, x):
        "The consumer spends x dollars if feasible"
        new_wealth = self.wealth - x
        if new_wealth < 0:
            print("Insufficent funds")
        else:
            self.wealth = new_wealth

In [18]:
c1 = Consumer(15)  # Create instance with initial wealth 10
c1.spend(5)
c1.wealth

10

In [19]:
c1.earn(10)
c1.wealth

20

In [20]:
c1.spend(1)

In [21]:
c1.wealth

19

In [22]:
c1.spend(20)

Insufficent funds


In [23]:
c1.__dict__

{'wealth': 19}

In [25]:
Consumer.__dict__

mappingproxy({'__module__': '__main__',
              '__init__': <function __main__.Consumer.__init__(self, w)>,
              'earn': <function __main__.Consumer.earn(self, y)>,
              'spend': <function __main__.Consumer.spend(self, x)>,
              '__dict__': <attribute '__dict__' of 'Consumer' objects>,
              '__weakref__': <attribute '__weakref__' of 'Consumer' objects>,
              '__doc__': None})

In [26]:
history

class Account: #abstraction
    bal = 0
    def deposit(self):
        print ("my balance is {}".format(self.bal))
ravi = Account()
print (type(ravi))     # Instance/Object
print (type(Account))   # classobj/class
print (type(Account()))
print (dir(ravi))
nani=Account()
type(nani)
type(Account)
dir(nani)
nani=Account()
type(nani)
type(Account)
print(dir(nani))
nani=Account()
print(type(nani))
(printtype(Account))
print(dir(nani))
nani=Account()
print(type(nani))
print(type(Account))
print(dir(nani))
ravi.bal
nani.bal
ravi.deposit()
nani.deposit()
class BAccount:
    def __init__(self):  # constructor
        self.Nbal = 0
    def deposit(self,amount):
        self.Nbal = self.Nbal + amount
        return "my balance is {}".format(self.Nbal)
    def withdraw(self,amount):
        self.Nbal = self.Nbal - amount
        return "my balance is {}".format(self.Nbal)
class Bac:
    def __init__(self):
        self.bal=0
    def deposit(self,amount):
        self.bal=self.bal+amount
        re

In [33]:
Consumer.earn(c2,10)
c1.wealth()

TypeError: 'int' object is not callable

In [34]:
c2 = Consumer(12)
c2.spend(4)
c2.wealth

8

In [35]:
x = (10, 20)
len(x)

2

In [43]:
class Foo:

    def __len__(self):
        return 42

In [44]:
f=Foo()

In [45]:
f(8)

TypeError: 'Foo' object is not callable

In [46]:
h = Foo()
h.__call__(8)

AttributeError: 'Foo' object has no attribute '__call__'

In [48]:
class Father:
    hand="right"
    occup = "Doctor"
    
class Mother:
    hand ="left"
    occup = "Engineer"
    
class Child(Father,Mother):
    occup ="Architect"
class Child1(Mother,Father):
    hand = "Right"
    occup="tea taster"

kumar = Child()
santosh = Child1()

print (dir(kumar))
print (dir(santosh))
print (kumar.hand)
print (kumar.occup)
print (santosh.hand)
print (santosh.occup)

['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', 'hand', 'occup']
['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', 'hand', 'occup']
right
Architect
Right
tea taster


In [49]:
class InvalidAge(Exception):
    # method
    def __init__(self,age):
        self.age = age

# Function
def Validate_Age(age):
    if age < 18:
       raise InvalidAge(age)

# Main
age = int(input("please enter your age:"))
try:
    Validate_Age(age)
except InvalidAge as e:
    print (" you still have time for this movie {}".format(e.age))
else:
    print (" enjoy the movie")

please enter your age:12
 you still have time for this movie 12


In [51]:
class invAge(Exception):
    def __init__(self,age):
        self.age=age
def Validate_age(age):
    if age <18:
        raise InvAge(age)
age=int(input('please enter your age:'))
try:
    Validate_age(age)
except invAge as e:
    print("you still have time for this movie{}".format(e.age))
else:
    print('enjoy the movie')
        
    

please enter your age:123
enjoy the movie


In [52]:
class Baccount:
    def __init__(self):  # constructor
        self.Nbal = 0
    def deposit(self,amount):
        self.Nbal = self.Nbal + amount
        return "my balance is {}".format(self.Nbal)
    def withdraw(self,amount):
        self.Nbal = self.Nbal - amount
        return "my balance is {}".format(self.Nbal)

In [53]:
class baccount:
    def __init__(self):
        self.bal=0
    def deposit(self,amount):
        self.bal=self.bal+amount
        return "my balance is {}".format(self.bal)
    def withdraw(self,amount):
        self.bal=self.balance-amount
        return "my balnce is: {}".format(self.bal)
    

In [54]:
pandu=baccount()

In [55]:
pandu.deposit(1000)

'my balance is 1000'

In [56]:
pandu.deposit(100)

'my balance is 1100'

In [58]:
class minbal(baccount):
    def __init__(self):
        baccount.__init__(self)
    def withdraw(self,amount):
        if self.bal-amount <1000:
            return "call your Daddy!!!"
        else :
            return baccount.withdraw(self,account)
        
            
    

In [59]:
# Student
# Inheritance: you get access to variable,methods of parent class
# but for constructor you need to call explictly.
class MinBalAccount(Baccount):
    def __init__(self):
        Baccount.__init__(self)
    def withdraw(self,amount):
        if self.Nbal - amount < 1000:
            return "Call your Daddy!!!"
        else:
            return Baccount.withdraw(self,amount)

In [60]:
moh=minbal()
moh.deposit(4000)

'my balance is 4000'

In [61]:
moh.withdraw(4000)

'call your Daddy!!!'

In [64]:
class Employee(object):

    def __init__(self, _num, _name, _salary):
        self.empNum = _num
        self.empName = _name
        self.empSalary = _salary
        
    def printData(self):
        print ('EmpId: {}, EmpName: {}, EmpSalary: {}'.format(self.empNum,
                                                             self.empName,
                                                             self.empSalary))
    def calculateTax(self):
        slab = (self.empSalary * 12) - 300000
        tax = 0
        if slab > 0:
            tax = slab * 0.1
        print ("tax for empid: {} is {}".format(self.empNum, tax))
       
    def __str__(self):
        return 'EmpId: {}, EmpName: {}, EmpSalary: {}'.format(self.empNum,
                                                             self.empName,
                                                        self.empSalary)

        
    def __repr__(self):
        return "Employee({}, '{}', {})".format(self.empNum,
                                               self.empName,
                                             self.empSalary)
e1 = Employee(1234, 'John', 23500.0)


In [65]:
e1

Employee(1234, 'John', 23500.0)

In [66]:
e1.calculateTax()

tax for empid: 1234 is 0


In [67]:
x = 20
y = 40
eval('x*y')

800

In [69]:
obj = eval("Employee(1234, 'John', 23500.0)")
print (obj)

EmpId: 1234, EmpName: John, EmpSalary: 23500.0


In [70]:
class Example(object):
    def __init__(self):
        self.x = 20
        self.y = 30
    def fun(self):
        self.p = 100
        
e1 = Example()
e2 = Example()

In [71]:
e1.fun()

In [72]:
e3=Example()

In [75]:
e3.p

100

In [74]:
e3.p=100

In [76]:
class FourWheeler(object):
    def __init__(self, _model, _clr, _size, _price, _ver, _yr):
        self.engineModel = _model
        self.color = _clr
        self.wheelSize = _size
        self.price = _price
        self.version = _ver
        self.year = _yr
        
    def __computeDiscount(self):
        if self.engineModel == 'HW':
            return self.price* 0.1
        if self.engineModel == 'LW':
            return self.price* 0.2
        return 0.0
        
    def getOnRoadPrice(self):
        if self.year == 2016:
            tax = 12.0
        elif self.year == 2017:
            tax = 13.0
        else:
            tax = 10.0
            
        return  self.price * (1 + tax/100) - self.__computeDiscount()
    
fw1 = FourWheeler('HW', 'RED', 2.0, 100000, 1.6, 2016)
fw1.getOnRoadPrice()

102000.00000000001

In [80]:
fw1.getOnRoadPrice()

102000.00000000001

In [81]:
class Car(FourWheeler):
    pass

In [82]:
cr = Car('HW', 'RED', 1.0, 110000, 2.0, 2016)
cr.getOnRoadPrice()

112200.00000000001

In [89]:
class Car(FourWheeler):
    def __init__(self, _model, _clr, _size, _price, _ver, _yr, _cmodel):
        self.engineModel = _model
        self.color = _clr
        self.wheelSize = _size
        self.price = _price
        self.version = _ver
        self.year = _yr
        #--------------
        self.carModel = _cmodel
        
    def __computeDiscount(self):
        if self.carModel == 'hatchback':
            return self.price* 0.1
        if self.carModel == 'sedon':
            return self.price* 0.15
        if self.carModel == 'TUV':
            return self.price* 0.12
        if self.carModel == 'XUV':
            return self.price* 0.11

    
cr = Car('XU', 'RED', 2.0, 1000000, 2.0, 2016, 'sedon')
cr.getOnRoadPrice()

1120000.0

In [90]:
import numpy as np

In [92]:
np

<module 'numpy' from 'C:\\Users\\ntadi\\AppData\\Roaming\\Python\\Python37\\site-packages\\numpy\\__init__.py'>

In [96]:
a=np.zeros(4)

In [97]:
a

array([0., 0., 0., 0.])

In [98]:
type(a)

numpy.ndarray

In [99]:
type(a[0])

numpy.float64

In [125]:
z=np.zeros(12)

In [126]:
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [127]:
z.shape=(3,4)

In [128]:
z

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [118]:
z=np.zeros(4)

In [119]:
z

array([0., 0., 0., 0.])

In [121]:
z.shape=(2,2)

In [122]:
z

array([[0., 0.],
       [0., 0.]])

In [129]:
z.ndim

2

In [130]:
z=np.empty(3)

In [131]:
z

array([0., 0., 0.])

In [136]:
z=np.linspace(2,4,5)

In [137]:
z

array([2. , 2.5, 3. , 3.5, 4. ])

In [139]:
max-min/total

NameError: name 'total' is not defined

In [140]:
max - min/total 

NameError: name 'total' is not defined

In [142]:
z=np.array([10,12])

In [143]:
z

array([10, 12])

In [147]:
z=np.array([[1,2],[3,4]])

In [148]:
z

array([[1, 2],
       [3, 4]])

In [149]:
na=np.linspace(10,12,13)

In [150]:
na

array([10.        , 10.16666667, 10.33333333, 10.5       , 10.66666667,
       10.83333333, 11.        , 11.16666667, 11.33333333, 11.5       ,
       11.66666667, 11.83333333, 12.        ])

In [151]:
na is np.asarray(na) 

True

In [152]:
na

array([10.        , 10.16666667, 10.33333333, 10.5       , 10.66666667,
       10.83333333, 11.        , 11.16666667, 11.33333333, 11.5       ,
       11.66666667, 11.83333333, 12.        ])

In [153]:
type(na)

numpy.ndarray

In [154]:
z=np.linspace(1,2,3)

In [155]:
z

array([1. , 1.5, 2. ])

In [156]:
z[0]

1.0

In [157]:
z[0:2]

array([1. , 1.5])

In [158]:
z[-1]

2.0

In [159]:
k=np.array([[1,2],[3,4]])

In [160]:
k

array([[1, 2],
       [3, 4]])

In [161]:
k[0][0]

1

In [162]:
k[0][1]

2

In [163]:
k[0,0]

1

In [165]:
k[1,1]

4

In [167]:
n=np.array((1,2,3))

In [168]:
n

array([1, 2, 3])

In [171]:
d = np.array([0, 1, 1, 0, 0], dtype=bool)    #int64, float64 
d

array([False,  True,  True, False, False])

In [174]:
z=np.empty(5)

In [175]:
z

array([2. , 2.5, 3. , 3.5, 4. ])

In [176]:
z[:]=22

In [177]:
z

array([22., 22., 22., 22., 22.])

In [178]:
type(z)

numpy.ndarray

In [179]:
type(z[0])

numpy.float64

In [180]:
nn=np.array([[1,2],[3,4]],dtype=complex)

In [181]:
nn

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [183]:
x=np.arange(0,10,2)

In [184]:
x

array([0, 2, 4, 6, 8])

In [185]:
ln=np.arange(-1,1,0.1)

In [186]:
ln

array([-1.00000000e+00, -9.00000000e-01, -8.00000000e-01, -7.00000000e-01,
       -6.00000000e-01, -5.00000000e-01, -4.00000000e-01, -3.00000000e-01,
       -2.00000000e-01, -1.00000000e-01, -2.22044605e-16,  1.00000000e-01,
        2.00000000e-01,  3.00000000e-01,  4.00000000e-01,  5.00000000e-01,
        6.00000000e-01,  7.00000000e-01,  8.00000000e-01,  9.00000000e-01])

In [187]:
len(ln)

20

In [191]:
x,y=np.mgrid[0:5,0:5]

In [192]:
x,y

(array([[0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3],
        [4, 4, 4, 4, 4]]), array([[0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4]]))

In [193]:
x

array([[0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4]])

In [194]:
y

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [203]:
a=np.array((1,20,3,4,5))

In [204]:
a

array([ 1, 20,  3,  4,  5])

In [205]:
a.T

array([ 1, 20,  3,  4,  5])

In [206]:
a.sort()

In [207]:
a

array([ 1,  3,  4,  5, 20])

In [208]:
a.sum()

33

In [209]:
a.mean()

6.6

In [210]:
a.max()

20

In [211]:
a.argmax()

4

In [212]:
a.min()

1

In [213]:
a.argmin()

0

In [215]:
a.cumsum()

array([ 1,  4,  8, 13, 33], dtype=int32)

In [216]:
a.prod()

1200

In [217]:
a.cumprod()

array([   1,    3,   12,   60, 1200], dtype=int32)

In [218]:
a.var()

46.64

In [219]:
a.std()

6.829348431585549

In [222]:
a.shape=(1,5)

In [223]:
a

array([[ 1,  3,  4,  5, 20]])

In [225]:
z=np.linspace(1,2,3)

In [226]:
z

array([1. , 1.5, 2. ])

In [227]:
z.sum()

4.5

In [229]:
z.mean()

1.5

In [230]:
z.var()

0.16666666666666666

In [231]:
z.std()

0.408248290463863

In [232]:
z.cumsum()

array([1. , 2.5, 4.5])

In [233]:
z.cumprod()

array([1. , 1.5, 3. ])

In [234]:
z.prod()

3.0

In [235]:
z.searchsorted(3.2)

3

In [237]:
n=np.array((1,22,33,44,78,2,3,4))

In [238]:
n

array([ 1, 22, 33, 44, 78,  2,  3,  4])

In [239]:
n.sort()

In [241]:
n.T

array([ 1,  2,  3,  4, 22, 33, 44, 78])

In [242]:
n.sum()

187

In [243]:
n.cumsum()

array([  1,   3,   6,  10,  32,  65, 109, 187], dtype=int32)

In [244]:
n.prod()

59799168

In [245]:
n.cumprod()

array([       1,        2,        6,       24,      528,    17424,
         766656, 59799168], dtype=int32)

In [246]:
n.shape=(4,2)

In [247]:
n

array([[ 1,  2],
       [ 3,  4],
       [22, 33],
       [44, 78]])

In [248]:
n

array([[ 1,  2],
       [ 3,  4],
       [22, 33],
       [44, 78]])

In [250]:
n.shape=(1,8)

In [251]:
n

array([[ 1,  2,  3,  4, 22, 33, 44, 78]])

In [252]:
n.mean()

23.375

In [253]:
n.var()

656.484375

In [254]:
n.max()

78

In [256]:
n.min()

1

In [258]:
n.argmax()

7

In [259]:
n.argmin()

0

In [260]:
n.std()

25.62195103812354

In [261]:
n.var()

656.484375

In [262]:
a=np.array((1,2,3,4,5))
b=np.array((6,7,8,9,10))

In [263]:
a,b

(array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10]))

In [264]:
c=[a+b]

In [265]:
c

[array([ 7,  9, 11, 13, 15])]

In [266]:
d=a+b

In [267]:
d

array([ 7,  9, 11, 13, 15])

In [268]:
a*b

array([ 6, 14, 24, 36, 50])

In [271]:
a=np.ones((2,2))

In [272]:
a

array([[1., 1.],
       [1., 1.]])

In [274]:
b=np.ones((2,2))

In [275]:
b

array([[1., 1.],
       [1., 1.]])

In [276]:
a+b

array([[2., 2.],
       [2., 2.]])

In [277]:
a*b

array([[1., 1.],
       [1., 1.]])

In [278]:
d = np.array([0, 1, 1, 0, 0], dtype=bool)    #int64, float64 
d

array([False,  True,  True, False, False])

In [279]:
import numpy as np

A = np.ones((2, 2))
B = np.ones((2, 2))
A @ B

array([[2., 2.],
       [2., 2.]])

In [280]:
a=np.array((1,2))

In [281]:
b=np.array((3,4))

In [282]:
a*b

array([3, 8])

In [283]:
a@b

11

In [287]:
a=np.diag((1,2,3))

In [288]:
np.diag(a)

array([1, 2, 3])

In [291]:
a=np.random.randn(50)

In [292]:
a

array([ 0.49377097, -0.38929474, -0.8137712 , -0.62984902, -0.42255995,
       -0.82720951,  0.21959484, -0.32347241, -0.21708566,  0.68034979,
       -1.54051801,  0.87193556, -1.05274244,  0.28737202, -0.17787822,
       -0.26751106, -0.15846724,  0.05328075, -0.28258809,  0.46409852,
       -0.84250574,  0.17482608,  0.52776092, -1.02846556,  0.64132   ,
        2.15744322,  0.32990661, -0.236798  ,  1.00677291,  0.3623873 ,
       -1.28514876,  0.85868768, -0.01719191,  0.0399475 ,  1.88652854,
       -0.35947851,  1.04356288,  0.62214865,  0.87475812,  0.54387128,
        0.88681836, -0.94497399, -1.96202613, -0.72673777,  0.73782659,
       -0.63903933, -0.32993835, -0.56728211,  1.29717982,  0.7044016 ])

In [293]:
import pandas as pd
import numpy as np

In [296]:
series1=pd.Series([1,2,3,4,5])

In [297]:
series1

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [298]:
series1=pd.Series([1,2],['nani','nani1'])

In [300]:
series1

nani     1
nani1    2
dtype: int64

In [301]:
series1.values

array([1, 2], dtype=int64)

In [302]:
series1.index

Index(['nani', 'nani1'], dtype='object')

In [303]:
series2 = pd.Series([10,20,30,40,50], index=['one','two','three','four','five'])
series2

one      10
two      20
three    30
four     40
five     50
dtype: int64

In [304]:
series3=pd.Series([1,2,3],['one','two','three'])

In [305]:
series3

one      1
two      2
three    3
dtype: int64

In [306]:
series3.values

array([1, 2, 3], dtype=int64)

In [307]:
series3.index

Index(['one', 'two', 'three'], dtype='object')

In [308]:
series3[0]

1

In [309]:
series3['one']

1

In [315]:
series3 +10

one      11
two      12
three    13
dtype: int64

In [316]:
series3 *2

one      2
two      4
three    6
dtype: int64

In [317]:
series4=series3 +1

In [318]:
series4

one      2
two      3
three    4
dtype: int64

In [319]:
series1.describe()

count    2.000000
mean     1.500000
std      0.707107
min      1.000000
25%      1.250000
50%      1.500000
75%      1.750000
max      2.000000
dtype: float64

In [321]:
series3.describe()

count    3.0
mean     2.0
std      1.0
min      1.0
25%      1.5
50%      2.0
75%      2.5
max      3.0
dtype: float64

In [325]:
years = [90, 91, 92, 93, 94, 95]
f1 = {90:8, 91:9, 92:7, 93:8, 94:9, 95:11}
firm1 = pd.Series(f1, index=years)
firm1

90     8
91     9
92     7
93     8
94     9
95    11
dtype: int64

In [326]:
firm1.describe()

count     6.000000
mean      8.666667
std       1.366260
min       7.000000
25%       8.000000
50%       8.500000
75%       9.000000
max      11.000000
dtype: float64

In [327]:
f2 = {90:14,92:9, 93:13, 94:5}
firm2 = pd.Series(f2,index=years)
firm2

90    14.0
91     NaN
92     9.0
93    13.0
94     5.0
95     NaN
dtype: float64

In [328]:
data = pd.DataFrame({'price':[95, 25, 85, 41, 78],
                     'ticker':['AXP', 'CSCO', 'DIS', 'MSFT', 'WMT'],
                     'company':['American Express', 'Cisco', 'Walt Disney','Microsoft', 'Walmart']})
data

price ticker           company
0     95    AXP  American Express
1     25   CSCO             Cisco
2     85    DIS       Walt Disney
3     41   MSFT         Microsoft
4     78    WMT           Walmart

In [329]:
data.describe

<bound method NDFrame.describe of    price ticker           company
0     95    AXP  American Express
1     25   CSCO             Cisco
2     85    DIS       Walt Disney
3     41   MSFT         Microsoft
4     78    WMT           Walmart>

In [330]:
data.describe()

price
count   5.00000
mean   64.80000
std    30.18609
min    25.00000
25%    41.00000
50%    78.00000
75%    85.00000
max    95.00000

In [332]:
data['price']

0    95
1    25
2    85
3    41
4    78
Name: price, dtype: int64

In [333]:
data['ticker']

0     AXP
1    CSCO
2     DIS
3    MSFT
4     WMT
Name: ticker, dtype: object

In [334]:
data.company

0    American Express
1               Cisco
2         Walt Disney
3           Microsoft
4             Walmart
Name: company, dtype: object

In [337]:
data.iloc[1]

price         25
ticker      CSCO
company    Cisco
Name: 1, dtype: object

In [338]:
data.ix[data.ticker < 'DIS']

C:\Users\ntadi\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


price ticker           company
0     95    AXP  American Express
1     25   CSCO             Cisco

In [342]:
data['Year'] 
data

price ticker           company Year
0     95    AXP  American Express     
1     25   CSCO             Cisco     
2     85    DIS       Walt Disney     
3     41   MSFT         Microsoft     
4     78    WMT           Walmart

In [343]:
data['Year']='' 
data

price ticker           company Year
0     95    AXP  American Express     
1     25   CSCO             Cisco     
2     85    DIS       Walt Disney     
3     41   MSFT         Microsoft     
4     78    WMT           Walmart

In [344]:
data['pricesquared'] = data.price**2
data


price ticker           company Year  pricesquared
0     95    AXP  American Express               9025
1     25   CSCO             Cisco                625
2     85    DIS       Walt Disney               7225
3     41   MSFT         Microsoft               1681
4     78    WMT           Walmart               6084

In [346]:
data['nani']=data.company*2

In [347]:
data

price ticker           company Year  pricesquared  \
0     95    AXP  American Express               9025   
1     25   CSCO             Cisco                625   
2     85    DIS       Walt Disney               7225   
3     41   MSFT         Microsoft               1681   
4     78    WMT           Walmart               6084   

                               nani  
0  American ExpressAmerican Express  
1                        CiscoCisco  
2            Walt DisneyWalt Disney  
3                MicrosoftMicrosoft  
4                    WalmartWalmart

In [348]:
con = 
a = "select * from tab1"

SyntaxError: invalid syntax (<ipython-input-348-0ea72c10698c>, line 1)

In [349]:
ab=pd.read_sql(a,con=con)

NameError: name 'con' is not defined

In [350]:
df = pd.read_csv('https://github.com/QuantEcon/QuantEcon.lectures.code/raw/master/pandas/data/test_pwt.csv')
type(df)

pandas.core.frame.DataFrame

In [351]:
df

country country isocode  year          POP       XRAT         tcgdp  \
0      Argentina             ARG  2000    37335.653   0.999500  2.950722e+05   
1      Australia             AUS  2000    19053.186   1.724830  5.418047e+05   
2          India             IND  2000  1006300.297  44.941600  1.728144e+06   
3         Israel             ISR  2000     6114.570   4.077330  1.292539e+05   
4         Malawi             MWI  2000    11801.505  59.543808  5.026222e+03   
5   South Africa             ZAF  2000    45064.098   6.939830  2.272424e+05   
6  United States             USA  2000   282171.957   1.000000  9.898700e+06   
7        Uruguay             URY  2000     3219.793  12.099592  2.525596e+04   

          cc         cg  
0  75.716805   5.578804  
1  67.759026   6.720098  
2  64.575551  14.072206  
3  64.436451  10.266688  
4  74.707624  11.658954  
5  72.718710   5.726546  
6  72.347054   6.032454  
7  78.978740   5.108068

In [352]:
df.describe()

year           POP       XRAT         tcgdp         cc         cg
count     8.0  8.000000e+00   8.000000  8.000000e+00   8.000000   8.000000
mean   2000.0  1.763826e+05  16.415811  1.606312e+06  71.404995   8.145477
std       0.0  3.479223e+05  22.758175  3.397025e+06   5.318015   3.383397
min    2000.0  3.219793e+03   0.999500  5.026222e+03  64.436451   5.108068
25%    2000.0  1.037977e+04   1.543622  1.032544e+05  66.963157   5.689611
50%    2000.0  2.819442e+04   5.508580  2.611573e+05  72.532882   6.376276
75%    2000.0  1.043411e+05  20.310094  8.383896e+05  74.959919  10.614755
max    2000.0  1.006300e+06  59.543808  9.898700e+06  78.978740  14.072206

In [353]:
df.describe

<bound method NDFrame.describe of          country country isocode  year          POP       XRAT         tcgdp  \
0      Argentina             ARG  2000    37335.653   0.999500  2.950722e+05   
1      Australia             AUS  2000    19053.186   1.724830  5.418047e+05   
2          India             IND  2000  1006300.297  44.941600  1.728144e+06   
3         Israel             ISR  2000     6114.570   4.077330  1.292539e+05   
4         Malawi             MWI  2000    11801.505  59.543808  5.026222e+03   
5   South Africa             ZAF  2000    45064.098   6.939830  2.272424e+05   
6  United States             USA  2000   282171.957   1.000000  9.898700e+06   
7        Uruguay             URY  2000     3219.793  12.099592  2.525596e+04   

          cc         cg  
0  75.716805   5.578804  
1  67.759026   6.720098  
2  64.575551  14.072206  
3  64.436451  10.266688  
4  74.707624  11.658954  
5  72.718710   5.726546  
6  72.347054   6.032454  
7  78.978740   5.108068  >

In [354]:
df.columns

Index(['country', 'country isocode', 'year', 'POP', 'XRAT', 'tcgdp', 'cc',
       'cg'],
      dtype='object')

In [355]:
df.shape

(8, 8)

In [356]:
labels = ['country', 'tcgdp']
df[labels]

country         tcgdp
0      Argentina  2.950722e+05
1      Australia  5.418047e+05
2          India  1.728144e+06
3         Israel  1.292539e+05
4         Malawi  5.026222e+03
5   South Africa  2.272424e+05
6  United States  9.898700e+06
7        Uruguay  2.525596e+04

In [358]:
df[['country','tcgdp']]

country         tcgdp
0      Argentina  2.950722e+05
1      Australia  5.418047e+05
2          India  1.728144e+06
3         Israel  1.292539e+05
4         Malawi  5.026222e+03
5   South Africa  2.272424e+05
6  United States  9.898700e+06
7        Uruguay  2.525596e+04

In [360]:
df.iloc[0:4,0:5]

country country isocode  year          POP      XRAT
0  Argentina             ARG  2000    37335.653   0.99950
1  Australia             AUS  2000    19053.186   1.72483
2      India             IND  2000  1006300.297  44.94160
3     Israel             ISR  2000     6114.570   4.07733

In [362]:
df.loc[0]

country            Argentina
country isocode          ARG
year                    2000
POP                  37335.7
XRAT                  0.9995
tcgdp                 295072
cc                   75.7168
cg                    5.5788
Name: 0, dtype: object

In [363]:
df.loc[df.index[2:5], ['country', 'tcgdp']]

country         tcgdp
2   India  1.728144e+06
3  Israel  1.292539e+05
4  Malawi  5.026222e+03

In [366]:
df.columns

Index(['country', 'country isocode', 'year', 'POP', 'XRAT', 'tcgdp', 'cc',
       'cg'],
      dtype='object')

In [369]:
df=df[['country','POP','year']]

In [370]:
df

country          POP  year
0      Argentina    37335.653  2000
1      Australia    19053.186  2000
2          India  1006300.297  2000
3         Israel     6114.570  2000
4         Malawi    11801.505  2000
5   South Africa    45064.098  2000
6  United States   282171.957  2000
7        Uruguay     3219.793  2000

In [374]:
df.set_index('country')

POP  year
country                         
Argentina        37335.653  2000
Australia        19053.186  2000
India          1006300.297  2000
Israel            6114.570  2000
Malawi           11801.505  2000
South Africa     45064.098  2000
United States   282171.957  2000
Uruguay           3219.793  2000

In [375]:
df['POP'].unique

<bound method Series.unique of 0      37335.653
1      19053.186
2    1006300.297
3       6114.570
4      11801.505
5      45064.098
6     282171.957
7       3219.793
Name: POP, dtype: float64>

In [376]:
df.columns='population','country'

ValueError: Length mismatch: Expected axis has 3 elements, new values have 2 elements

In [378]:
df.columns = 'population', 'total GDP','country'
df

population    total GDP  country
0      Argentina    37335.653     2000
1      Australia    19053.186     2000
2          India  1006300.297     2000
3         Israel     6114.570     2000
4         Malawi    11801.505     2000
5   South Africa    45064.098     2000
6  United States   282171.957     2000
7        Uruguay     3219.793     2000

In [381]:
df['GDP percap'] = df['total GDP'] * 6 / df['country']
df

C:\Users\ntadi\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


population    total GDP  country   GDP percap
0      Argentina    37335.653     2000   112.006959
1      Australia    19053.186     2000    57.159558
2          India  1006300.297     2000  3018.900891
3         Israel     6114.570     2000    18.343710
4         Malawi    11801.505     2000    35.404515
5   South Africa    45064.098     2000   135.192294
6  United States   282171.957     2000   846.515871
7        Uruguay     3219.793     2000     9.659379

In [383]:
df.groupby("country")

In [384]:
df

population    total GDP  country   GDP percap
0      Argentina    37335.653     2000   112.006959
1      Australia    19053.186     2000    57.159558
2          India  1006300.297     2000  3018.900891
3         Israel     6114.570     2000    18.343710
4         Malawi    11801.505     2000    35.404515
5   South Africa    45064.098     2000   135.192294
6  United States   282171.957     2000   846.515871
7        Uruguay     3219.793     2000     9.659379

In [385]:
import matplotlib.pyplot as plt

plt.show()

In [386]:
df = df.sort_values(by='GDP percap', ascending=False)
df

population    total GDP  country   GDP percap
2          India  1006300.297     2000  3018.900891
6  United States   282171.957     2000   846.515871
5   South Africa    45064.098     2000   135.192294
0      Argentina    37335.653     2000   112.006959
1      Australia    19053.186     2000    57.159558
4         Malawi    11801.505     2000    35.404515
3         Israel     6114.570     2000    18.343710
7        Uruguay     3219.793     2000     9.659379

In [387]:
df1 = pd.read_csv("f.csv")
df2 = pd.read_csv("f2.csv")

df3 = pd.concat(df1,df2,df9)    # employee id

df4    

FileNotFoundError: [Errno 2] File b'f.csv' does not exist: b'f.csv'

In [388]:
df.head(2)

population    total GDP  country   GDP percap
2          India  1006300.297     2000  3018.900891
6  United States   282171.957     2000   846.515871

In [389]:
df.head()

population    total GDP  country   GDP percap
2          India  1006300.297     2000  3018.900891
6  United States   282171.957     2000   846.515871
5   South Africa    45064.098     2000   135.192294
0      Argentina    37335.653     2000   112.006959
1      Australia    19053.186     2000    57.159558

In [391]:
df.tail(2)

population  total GDP  country  GDP percap
3     Israel   6114.570     2000   18.343710
7    Uruguay   3219.793     2000    9.659379

In [392]:
%%
exit

UsageError: Cell magic `%%` not found.


In [393]:
!shutdown

Usage: shutdown [/i | /l | /s | /sg | /r | /g | /a | /p | /h | /e | /o] [/hybrid] [/soft] [/fw] [/f]
    [/m \\computer][/t xxx][/d [p|u:]xx:yy [/c "comment"]]

    No args    Display help. This is the same as typing /?.
    /?         Display help. This is the same as not typing any options.
    /i         Display the graphical user interface (GUI).
               This must be the first option.
    /l         Log off. This cannot be used with /m or /d options.
    /s         Shutdown the computer.
    /sg        Shutdown the computer. On the next boot, if Automatic Restart Sign-On
               is enabled, automatically sign in and lock last interactive user.
               After sign in, restart any registered applications.
    /r         Full shutdown and restart the computer.
    /g         Full shutdown and restart the computer. After the system is rebooted,
               if Automatic Restart Sign-On is enabled, automatically sign in and
               lock last interactive user

In [395]:
import pandas as pd
import numpy as np

In [397]:
df=pd.read_csv('diabetes.csv')

In [399]:
df.describe()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
count   768.000000  768.000000     768.000000     768.000000  768.000000   
mean      3.845052  120.894531      69.105469      20.536458   79.799479   
std       3.369578   31.972618      19.355807      15.952218  115.244002   
min       0.000000    0.000000       0.000000       0.000000    0.000000   
25%       1.000000   99.000000      62.000000       0.000000    0.000000   
50%       3.000000  117.000000      72.000000      23.000000   30.500000   
75%       6.000000  140.250000      80.000000      32.000000  127.250000   
max      17.000000  199.000000     122.000000      99.000000  846.000000   

              BMI  DiabetesPedigreeFunction         Age     Outcome  
count  768.000000                768.000000  768.000000  768.000000  
mean    31.992578                  0.471876   33.240885    0.348958  
std      7.884160                  0.331329   11.760232    0.476951  
min      0.000000                  0.078000   21.000000    0.000000  
25%     27.300000                  0.243750   24.000000    0.000000  
50%     32.000000                  0.372500   29.000000    0.000000  
75%     36.600000                  0.626250   41.000000    1.000000  
max     67.100000                  2.420000   81.000000    1.000000

In [400]:
df.count()

Pregnancies                 768
Glucose                     768
BloodPressure               768
SkinThickness               768
Insulin                     768
BMI                         768
DiabetesPedigreeFunction    768
Age                         768
Outcome                     768
dtype: int64

In [404]:
dir(df)

['Age',
 'BMI',
 'BloodPressure',
 'DiabetesPedigreeFunction',
 'Glucose',
 'Insulin',
 'Outcome',
 'Pregnancies',
 'SkinThickness',
 'T',
 '_AXIS_ALIASES',
 '_AXIS_IALIASES',
 '_AXIS_LEN',
 '_AXIS_NAMES',
 '_AXIS_NUMBERS',
 '_AXIS_ORDERS',
 '_AXIS_REVERSED',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_priority__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__div__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__

In [406]:
df.shape

(768, 9)

In [407]:
a=range(1,200)

In [408]:
a

range(1, 200)

In [409]:
a=range(10)

In [410]:
a

range(0, 10)

In [415]:
a=list(range(10))

In [416]:
a

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [418]:
import sys
import numpy as np

In [421]:
dir(sys)

['__breakpointhook__',
 '__displayhook__',
 '__doc__',
 '__excepthook__',
 '__interactivehook__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '__stderr__',
 '__stdin__',
 '__stdout__',
 '_base_executable',
 '_clear_type_cache',
 '_current_frames',
 '_debugmallocstats',
 '_enablelegacywindowsfsencoding',
 '_framework',
 '_getframe',
 '_git',
 '_home',
 '_xoptions',
 'api_version',
 'argv',
 'base_exec_prefix',
 'base_prefix',
 'breakpointhook',
 'builtin_module_names',
 'byteorder',
 'call_tracing',
 'callstats',
 'copyright',
 'displayhook',
 'dllhandle',
 'dont_write_bytecode',
 'exc_info',
 'excepthook',
 'exec_prefix',
 'executable',
 'exit',
 'flags',
 'float_info',
 'float_repr_style',
 'get_asyncgen_hooks',
 'get_coroutine_origin_tracking_depth',
 'get_coroutine_wrapper',
 'getallocatedblocks',
 'getcheckinterval',
 'getdefaultencoding',
 'getfilesystemencodeerrors',
 'getfilesystemencoding',
 'getprofile',
 'getrecursionlimit',
 'getrefcount',
 'getsizeof',
 'getsw

In [422]:
n=sys.getsizeof(a)

In [423]:
n

200

In [424]:
k=np.array(a)

In [425]:
k

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [426]:
n1=sys.getsizeof(k)

In [427]:
n1

136

In [428]:
l=tuple(a)

In [429]:
l

(0, 1, 2, 3, 4, 5, 6, 7, 8, 9)

In [430]:
n3=sys.getsizeof(l)

In [431]:
n3

128

In [432]:
size=10000

In [433]:
l=range(size)

In [434]:
l

range(0, 10000)

In [435]:
l=list(l)

In [436]:
l

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,


In [438]:
nn=sys.getsizeof(l)

In [439]:
nn

90112

In [440]:
kk=np.arange(size)

In [441]:
kk

array([   0,    1,    2, ..., 9997, 9998, 9999])

In [443]:
nn=sys.getsizeof(kk)

In [444]:
nn

40096

In [445]:
k=np.array([[1,2],[2,3]])

In [446]:
k

array([[1, 2],
       [2, 3]])

In [448]:
k.shape

(2, 2)

In [449]:
k.ndim

2

In [450]:
kk.ndim

1

In [451]:
nn=np.array([[1,2,3],[1,3,4]],dtype=np.float)

In [452]:
nn

array([[1., 2., 3.],
       [1., 3., 4.]])

In [453]:
ss=sys.getsizeof(nn)

In [454]:
ss

160

In [457]:
nn.shape

(2, 3)

In [458]:
nn.itemsize

8

In [459]:
a=np.array([[1,2],[3,4]],dtype=np.complex)

In [460]:
a

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [461]:
np.ones(a
       )

TypeError: only integer scalar arrays can be converted to a scalar index

In [462]:
np.ones(3)

array([1., 1., 1.])

In [465]:
np.zeros(3)

array([0., 0., 0.])

In [466]:
name='narayanareddy'

In [469]:
k=np.array([name])

In [470]:
k

array(['narayanareddy'], dtype='<U13')

In [471]:
print(np.__version__)

1.18.2


In [476]:
k=np.array((2,3))

In [477]:
k

array([2, 3])

In [478]:
k.ndim

1

In [491]:
ll=np.array([[[1,2,3,4], [5,6,7,8]], [[1,2,3,4], [1,2,3,4]]])

In [492]:
ll

array([[[1, 2, 3, 4],
        [5, 6, 7, 8]],

       [[1, 2, 3, 4],
        [1, 2, 3, 4]]])

In [494]:
ll.ndim

3

In [495]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

In [496]:
arr

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [497]:
arr = np.array([1, 2, 3, 4], ndmin=5)

In [498]:
arr

array([[[[[1, 2, 3, 4]]]]])

In [499]:
df=pd.read_csv('diabetes.csv')

In [500]:
df.describe

<bound method NDFrame.describe of      Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627  

In [501]:
df.describe()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
count   768.000000  768.000000     768.000000     768.000000  768.000000   
mean      3.845052  120.894531      69.105469      20.536458   79.799479   
std       3.369578   31.972618      19.355807      15.952218  115.244002   
min       0.000000    0.000000       0.000000       0.000000    0.000000   
25%       1.000000   99.000000      62.000000       0.000000    0.000000   
50%       3.000000  117.000000      72.000000      23.000000   30.500000   
75%       6.000000  140.250000      80.000000      32.000000  127.250000   
max      17.000000  199.000000     122.000000      99.000000  846.000000   

              BMI  DiabetesPedigreeFunction         Age     Outcome  
count  768.000000                768.000000  768.000000  768.000000  
mean    31.992578                  0.471876   33.240885    0.348958  
std      7.884160                  0.331329   11.760232    0.476951  
min      0.000000                  0.078000   21.000000    0.000000  
25%     27.300000                  0.243750   24.000000    0.000000  
50%     32.000000                  0.372500   29.000000    0.000000  
75%     36.600000                  0.626250   41.000000    1.000000  
max     67.100000                  2.420000   81.000000    1.000000

In [506]:
df.head(10)

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   
5            5      116             74              0        0  25.6   
6            3       78             50             32       88  31.0   
7           10      115              0              0        0  35.3   
8            2      197             70             45      543  30.5   
9            8      125             96              0        0   0.0   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1  
5                     0.201   30        0  
6                     0.248   26        1  
7                     0.134   29        0  
8                     0.158   53        1  
9                     0.232   54        1

In [505]:
df.columns

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')

In [510]:
model_features=['Pregnancies','Glucose','BloodPressure','Insulin','SkinThickness','BMI','Age']

In [511]:
y=df.Outcome

In [512]:
X=df[model_features]

In [513]:
X.describe()

Pregnancies     Glucose  BloodPressure     Insulin  SkinThickness  \
count   768.000000  768.000000     768.000000  768.000000     768.000000   
mean      3.845052  120.894531      69.105469   79.799479      20.536458   
std       3.369578   31.972618      19.355807  115.244002      15.952218   
min       0.000000    0.000000       0.000000    0.000000       0.000000   
25%       1.000000   99.000000      62.000000    0.000000       0.000000   
50%       3.000000  117.000000      72.000000   30.500000      23.000000   
75%       6.000000  140.250000      80.000000  127.250000      32.000000   
max      17.000000  199.000000     122.000000  846.000000      99.000000   

              BMI         Age  
count  768.000000  768.000000  
mean    31.992578   33.240885  
std      7.884160   11.760232  
min      0.000000   21.000000  
25%     27.300000   24.000000  
50%     32.000000   29.000000  
75%     36.600000   41.000000  
max     67.100000   81.000000

In [515]:
X.head()

Pregnancies  Glucose  BloodPressure  Insulin  SkinThickness   BMI  Age
0            6      148             72        0             35  33.6   50
1            1       85             66        0             29  26.6   31
2            8      183             64        0              0  23.3   32
3            1       89             66       94             23  28.1   21
4            0      137             40      168             35  43.1   33

In [516]:
X.tail()

Pregnancies  Glucose  BloodPressure  Insulin  SkinThickness   BMI  Age
763           10      101             76      180             48  32.9   63
764            2      122             70        0             27  36.8   27
765            5      121             72      112             23  26.2   30
766            1      126             60        0              0  30.1   47
767            1       93             70        0             31  30.4   23

In [521]:
from sklearn.tree import DecisionTreeRegressor

In [522]:
model=DecisionTreeRegressor(random_state=1)

In [523]:
model.fit(X,y)

DecisionTreeRegressor(criterion='mse', max_depth=None, max_features=None,
                      max_leaf_nodes=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      presort=False, random_state=1, splitter='best')

In [524]:
model.predict(X.head())

array([1., 0., 1., 0., 1.])

In [525]:
years=[1,2,3,4,5,6,7,88]

In [526]:
a=pd.Series(years)

In [527]:
a

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7    88
dtype: int64

In [542]:
aa=pd.DataFrame({'x':[1,2,3],'y':[1,2,3]
               })

In [531]:
years = [90, 91, 92, 93, 94, 95]
f1 = {90:8, 91:9, 92:7, 93:8, 94:9, 95:11}
firm1 = pd.Series(f1,index=years)
firm1

90     8
91     9
92     7
93     8
94     9
95    11
dtype: int64

In [532]:
f2 = {90:14,92:9, 93:13, 94:5}
firm2 = pd.Series(f2,index=years)
firm2

90    14.0
91     NaN
92     9.0
93    13.0
94     5.0
95     NaN
dtype: float64

In [534]:
pd.isnull(firm2)

90    False
91     True
92    False
93    False
94    False
95     True
dtype: bool

In [535]:
dict1 = {'finance': 10, 'earning': 5, 'debt':8}
dict2 = {'finance' : 8, 'compensation':4, 'earning': 9}
count1 = pd.Series(dict1)
count2 = pd.Series(dict2)
print (count1)
print (count2)

finance    10
earning     5
debt        8
dtype: int64
finance         8
compensation    4
earning         9
dtype: int64


In [538]:
c=count1+count2

In [540]:
c.isnull()

compensation     True
debt             True
earning         False
finance         False
dtype: bool

In [543]:
aa

x  y
0  1  1
1  2  2
2  3  3

In [545]:
aa.head(1)

x  y
0  1  1

In [546]:
aa.tail()

x  y
0  1  1
1  2  2
2  3  3

In [547]:
aa.describe()

x    y
count  3.0  3.0
mean   2.0  2.0
std    1.0  1.0
min    1.0  1.0
25%    1.5  1.5
50%    2.0  2.0
75%    2.5  2.5
max    3.0  3.0

In [548]:
aa.describe

<bound method NDFrame.describe of    x  y
0  1  1
1  2  2
2  3  3>

In [549]:
aa.columns

Index(['x', 'y'], dtype='object')

In [550]:
aa.x

0    1
1    2
2    3
Name: x, dtype: int64

In [551]:
aa.y

0    1
1    2
2    3
Name: y, dtype: int64

In [553]:
aa.iloc(1)

In [554]:
aa

x  y
0  1  1
1  2  2
2  3  3

In [555]:
aa.iloc[1]

x    2
y    2
Name: 1, dtype: int64

In [556]:
aa.iloc[2]

x    3
y    3
Name: 2, dtype: int64

In [557]:
aa.iloc[1]

x    2
y    2
Name: 1, dtype: int64

In [558]:
aa.iloc[0]

x    1
y    1
Name: 0, dtype: int64

In [559]:
aa.loc[0]

x    1
y    1
Name: 0, dtype: int64

In [560]:
aa.loc[1]

x    2
y    2
Name: 1, dtype: int64

In [569]:
aa['x']

0    
1    
2    
Name: x, dtype: object

In [571]:
aa

x  y
0    1
1    2
2    3

In [577]:
aa['x1']= aa.y **2

In [578]:
aa

x  y  x1
0    1   1
1    2   4
2    3   9

In [582]:
aa['y1']=aa.x+x

ValueError: operands could not be broadcast together with shapes (3,) (5,5) 

In [583]:
aa['x']

0    
1    
2    
Name: x, dtype: object

In [585]:
aa['x2']=aa.y
+1

1

In [586]:
aa

x  y  x1  x2
0    1   1   1
1    2   4   2
2    3   9   3

In [588]:
 del aa['x1']

In [589]:
aa

x  y  x2
0    1   1
1    2   2
2    3   3

In [591]:
aa=pd.DataFrame({'x1':[1,2,3]})

In [592]:
aa

x1
0   1
1   2
2   3

In [593]:
aa['x2']=[1,2,3]

In [594]:
aa

x1  x2
0   1   1
1   2   2
2   3   3